In [ ]:
import numpy as np
import pandas as pd
from utils import get_args_parser
from remasker_impute import ReMasker

X_raw = np.arange(50).reshape(10, 5) * 1.0
print(X_raw)
X = pd.DataFrame(X_raw, columns=['0', '1', '2', '3', '4'])
X.iat[3,0] = np.nan
print(X)
imputer = ReMasker()


imputed = imputer.fit_transform(X)
print(imputed[3,0])

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]
 [25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34.]
 [35. 36. 37. 38. 39.]
 [40. 41. 42. 43. 44.]
 [45. 46. 47. 48. 49.]]


usage: MAE pre-training [--dataset DATASET] [--batch_size BATCH_SIZE]
                        [--max_epochs MAX_EPOCHS] [--accum_iter ACCUM_ITER]
                        [--mask_ratio MASK_RATIO] [--embed_dim EMBED_DIM]
                        [--depth DEPTH] [--decoder_depth DECODER_DEPTH]
                        [--num_heads NUM_HEADS] [--mlp_ratio MLP_RATIO]
                        [--encode_func ENCODE_FUNC]
                        [--norm_field_loss NORM_FIELD_LOSS]
                        [--weight_decay WEIGHT_DECAY] [--lr LR] [--blr LR]
                        [--min_lr LR] [--warmup_epochs N] [--path PATH]
                        [--exp_name EXP_NAME] [--device DEVICE] [--seed SEED]
                        [--overwrite OVERWRITE] [--pin_mem]
MAE pre-training: error: unrecognized arguments: --f=/Users/yuandouwang/Library/Jupyter/runtime/kernel-v3ffd7d0ce33f7e91090ff1a5ab070c6005b7dea33.json


SystemExit: 2